training:
  epochs:
    train: 100
    update: 50
    update_generator: 5
  learning_rates:
    train: 0.002
    update: 0.002
    update_generator: 0.0001

model:
  save_enabled: false
  load_enabled: false
  save_interval: 48
  save_path: "model_states" 
  lstm:
    size: 100
    layers: 2
    lookback_len: 3
    prediction_len: 1
  
anomaly_detection:
  threshold_multiplier: 1.0

system:
  use_neon: true
  random_seed: 42

data_source: "Tide_pressure"

data:
  paths:
    training: "data/Tide_pressure.validation_stage.csv"
    log: "adapad_logs"
  parameters:
    Tide_pressure:
      value:
        bounds:
          lower: 713.0
          upper: 763.0
        minimal_threshold: 0.0027
    Austevoll_nord:
      conductivity_conductivity:
        bounds:
          lower: 0
          upper: 40
        minimal_threshold: 0.005
      conductivity_temperature:
        bounds:
          lower: 0
          upper: 30
        minimal_threshold: 0.001
      conductivity_salinity:
        bounds:
          lower: 0
          upper: 1600
        minimal_threshold: 0.005
      conductivity_density:
        bounds:
          lower: 1000
          upper: 1040
        minimal_threshold: 0.01
      conductivity_soundspeed:
        bounds:
          lower: 1450
          upper: 1500
        minimal_threshold: 0.005
      pressure_pressure:
        bounds:
          lower: 200
          upper: 370
        minimal_threshold: 0.003
      pressure_temperature:
        bounds:
          lower: 0
          upper: 23
        minimal_threshold: 0.001
      dcps_current_speed:
        bounds:
          lower: 0
          upper: 100
        minimal_threshold: 0.05
      dcps_current_direction:
        bounds:
          lower: 0
          upper: 400
        minimal_threshold: 0.05
      dcps_current_speed_north:
        bounds:
          lower: -100
          upper: 100
        minimal_threshold: 0.05
      dcps_current_speed_east:
        bounds:
          lower: -100
          upper: 100
        minimal_threshold: 0.05
      dcps_current_speed_vertical:
        bounds:
          lower: -10
          upper: 10
        minimal_threshold: 0.05
      dcps_current_speed_std:
        bounds:
          lower: 0
          upper: 160
        minimal_threshold: 0.05
      dcps_signal_strength:
        bounds:
          lower: -20
          upper: 0
        minimal_threshold: 0.05
      dcps_cross_difference:
        bounds:
          lower: -20
          upper: 20
        minimal_threshold: 0.05
      


